=== FabianFriedrich/Text2Process/resources/fndata-1.5/schema/frame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:fn="http://framenet.icsi.berkeley.edu"
            targetNamespace="http://framenet.icsi.berkeley.edu"
            xmlns="http://framenet.icsi.berkeley.edu"
            elementFormDefault="qualified">
<!-- 
    1. Root element is 'frame'
    2. 'frame' has 3 attributes:
        1. 'ID', a nonNegativeInteger
        2. 'name' a word (that could contain underscores/dashes etc.) starting with a capital letter
        3. 'cDate' dayabbr monthabbr daynum hour:min:sec timezone year
    3. 'frame' has 3 elements:
        1. 'definition' a string
        2. 'fe'a complex type described below (1+)
        3. 'lexUnit' a complex type described below (0+)
    3.2.1 'fe' has 7 attributes:
        1. 'ID' (same as above description)
        2. 'name' (same as above description)
        3. 'abbrev' (same type as 'name')
        4. 'cDate' (same as above description)
        5. 'coreType' (same type as 'name')
        6. 'fgColor' (a word (lowercase) indicating a color)
        7. 'bgColor' (same type as 'fgColor')
    3.2.2 'fe' has 2 elements:
        1. 'definition' (a string)
        2. 'semType' (just as two attributes 'ID' and 'name') (implied 0+)
    3.3.1 'lexUnit' has 6 attributes:
        1. 'ID' (same as above description)
        2. 'name' (word with a period followed by a letter)
        3. 'POS' (a capital letter)
        4. 'status' (capital letter word)
        5. 'cDate' (same as above)
        6. 'lemmaId' (a nonNegativeInteger)
    3.3.2 'lexUnit' has 4 elements
        1. 'definition' (has SOURCE then a colon followed by a string)
        2. 'annotation' (has 2 elements, 'annotated' and 'total' both nonNegativeIntegers)
        3. 'lexeme' (a complex type described below) (1+)
        4. 'semType' (same as above) (implied 0+)
    3.3.2.3.1 'lexeme' has 4 attributes
        1. 'ID' (same)
        2. 'POS' (a capital letter)
        3. 'breakBefore' (a boolean)
        4. 'headWord' (a boolean)
    3.3.2.3.2 'lexeme' has text
-->
    <xsd:include schemaLocation="commonTypes.xsd"/>
    <xsd:element name="frame">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="definition" type="xsd:string"/>
                <xsd:element name="semType" type="fn:semTypeRefType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="FE" type="fn:FEType" maxOccurs="unbounded"/>
                <xsd:element name="FEcoreSet" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="memberFE" type="fn:internalFrameRelationFEType" minOccurs="2" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="frameRelation" type="fn:relatedFramesType"
                    maxOccurs="unbounded"/>
                <xsd:element name="lexUnit" type="fn:frameLUType" 
                    minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="ID" type="fn:IDType" use="required"/>
            <xsd:attribute name="name" type="fn:frameNameType" use="required"/>
            <xsd:attribute name="cDate" type="fn:dateTimeType" use="required"/>
            <xsd:attribute name="cBy" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element> <!-- end 'frame' -->

    <!-- FE Type -->
    <xsd:complexType name="FEType">
        <xsd:sequence>
            <xsd:element name="definition" type="xsd:string"/>
            <xsd:element name="semType" type="fn:semTypeRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="requiresFE" type="fn:internalFrameRelationFEType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="excludesFE" type="fn:internalFrameRelationFEType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="ID" type="fn:IDType" use="required"/>
        <xsd:attribute name="name" type="fn:frameNameType" use="required"/>
        <xsd:attribute name="abbrev" type="xsd:string" use="required"/>
        <xsd:attribute name="cDate" type="fn:dateTimeType" use="required"/>
        <xsd:attribute name="cBy" type="xsd:string" use="required"/>
        <xsd:attribute name="coreType" type="fn:coreType" use="required"/>
        <xsd:attribute name="fgColor" type="fn:RGBColorType" use="required"/>
        <xsd:attribute name="bgColor" type="fn:RGBColorType" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="internalFrameRelationFEType">
        <xsd:attribute name="ID" type="xsd:int" use="required"/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <!-- Related frames type -->
    <xsd:complexType name="relatedFramesType">
        <xsd:sequence>
            <xsd:element name="relatedFrame" type="fn:frameNameType"
                minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <!-- frame-embedded lexUnit type -->
    <xsd:complexType name="frameLUType">
        <xsd:sequence>
            <xsd:element name="definition" type="fn:defType"/>
            <xsd:element name="sentenceCount">
                <xsd:complexType>
                    <xsd:attribute name="total" type="fn:countType" use="required"/>
                    <xsd:attribute name="annotated" type="fn:countType" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="lexeme" type="fn:lexemeType" maxOccurs="unbounded"/>
            <xsd:element name="semType" type="fn:semTypeRefType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attributeGroup ref="fn:basicLUAttributes"/>
        <xsd:attribute name="cDate" type="fn:dateTimeType" use="required"/>
        <xsd:attribute name="cBy" type="xsd:string" use="required"/>
        <xsd:attribute name="lemmaID" type="fn:IDType" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/frame/Predicament.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="frame.xsl"?>
<frame cBy="664" cDate="04/09/2002 03:07:36 PDT Tue" name="Predicament" ID="300" xsi:schemaLocation="../schema/frame.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <definition>&lt;def-root&gt;An &lt;fen&gt;Experiencer&lt;/fen&gt; is in an undesirable &lt;fen&gt;Situation&lt;/fen&gt;, whose &lt;fen&gt;Cause&lt;/fen&gt; may also be expressed.

&lt;ex&gt;&lt;fex name="Exp"&gt;The insurers&lt;/fex&gt; &lt;m&gt;ended up&lt;/m&gt; &lt;m&gt;in&lt;/m&gt; the &lt;t&gt;bind&lt;/t&gt; &lt;fex name="Sit"&gt;of having to pay 15 years' taxes&lt;/fex&gt;.&lt;/ex&gt;

&lt;ex&gt;&lt;fex name="Exp"&gt;He&lt;/fex&gt; &lt;m&gt;was&lt;/m&gt; &lt;m&gt;in&lt;/m&gt; a bit of a &lt;fex name="Situation"&gt;&lt;t&gt;pickle&lt;/t&gt;&lt;/fex&gt; and make no mistake!&lt;/ex&gt;

&lt;ex&gt;What a &lt;fex name="Situation"&gt;&lt;t&gt;mess&lt;/t&gt;&lt;/fex&gt; &lt;fex name="Exp"&gt;we&lt;/fex&gt; &lt;m&gt;'re&lt;/m&gt; &lt;m&gt;in&lt;/m&gt; &lt;fex name="Time"&gt;now&lt;/fex&gt;!&lt;/ex&gt;&lt;/def-root&gt;</definition>
    <FE bgColor="FF0000" fgColor="FFFFFF" coreType="Core" cBy="664" cDate="04/09/2002 03:09:03 PDT Tue" abbrev="Exp" name="Experiencer" ID="2589">
        <definition>&lt;def-root&gt;The &lt;fen&gt;Experiencer&lt;/fen&gt; is in an undesirable &lt;fen&gt;Situation&lt;/fen&gt;.

&lt;ex&gt;&lt;fex name="Exp"&gt;The insurers&lt;/fex&gt; &lt;m&gt;ended up&lt;/m&gt; &lt;m&gt;in&lt;/m&gt; a &lt;t&gt;bind&lt;/t&gt;.&lt;/ex&gt;&lt;/def-root&gt;</definition>
        <semType name="Sentient" ID="5"/>
    </FE>
    <FE bgColor="008000" fgColor="FFFFFF" coreType="Core" cBy="664" cDate="04/09/2002 03:13:19 PDT Tue" abbrev="Sit" name="Situation" ID="2590">
        <definition>&lt;def-root&gt;This FE identifies the undesirable &lt;fen&gt;Situation&lt;/fen&gt; the &lt;fen&gt;Experiencer&lt;/fen&gt; is in.
&lt;ex&gt;They found themselves &lt;m&gt;in&lt;/m&gt; a quite &lt;fex name="Situation"&gt;a fix&lt;/fex&gt;.&lt;/ex&gt;
&lt;ex&gt;The company &lt;m&gt;was&lt;/m&gt; definitely &lt;m&gt;in&lt;/m&gt; &lt;fex name="Situation"&gt;dire straits&lt;/fex&gt; from the dollar's inflation.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="800080" fgColor="FFFFFF" coreType="Extra-Thematic" cBy="664" cDate="04/09/2002 03:14:39 PDT Tue" abbrev="Cause" name="Cause" ID="2591">
        <definition>&lt;def-root&gt;This FE identifies the &lt;fen&gt;Cause&lt;/fen&gt; of  the &lt;fen&gt;Situation&lt;/fen&gt;.

&lt;ex&gt;We 're in this &lt;t&gt;mess&lt;/t&gt; &lt;fex name="Cause"&gt;from paying too little attention to quality control&lt;/fex&gt;.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="FFA500" fgColor="FFFFFF" coreType="Peripheral" cBy="669" cDate="04/10/2002 01:29:24 PDT Wed" abbrev="Time" name="Time" ID="2593">
        <definition>&lt;def-root&gt;Thiis FE identifies the &lt;fen&gt;Time&lt;/fen&gt; when the &lt;fen&gt;Situation&lt;/fen&gt; is in effect.

&lt;ex&gt;&lt;fex name="Time"&gt;Yesterday's&lt;/fex&gt; &lt;t&gt;predicament&lt;/t&gt; was a little too exciting.&lt;/ex&gt;&lt;/def-root&gt;</definition>
        <semType name="Time" ID="141"/>
    </FE>
    <FE bgColor="0000FF" fgColor="FFFFFF" coreType="Peripheral" cBy="664" cDate="02/02/2006 04:27:32 PST Thu" abbrev="pla" name="Place" ID="9900">
        <definition>&lt;def-root&gt;The location where the &lt;fen&gt;Situation&lt;/fen&gt; occurs.

&lt;ex&gt;The &lt;t&gt;trouble&lt;/t&gt; &lt;fex name="pla"&gt;in America&lt;/fex&gt; is only going to get worse.&lt;/ex&gt;&lt;/def-root&gt;</definition>
        <semType name="Locative_relation" ID="182"/>
    </FE>
    <FE bgColor="00BFFF" fgColor="FFFFFF" coreType="Extra-Thematic" cBy="361" cDate="08/06/2007 01:37:25 PDT Mon" abbrev="" name="Domain" ID="11950">
        <definition>&lt;def-root&gt;The &lt;fen&gt;Domain&lt;/fen&gt; in which the &lt;fen&gt;Experiencer&lt;/fen&gt; has the problem.&lt;/def-root&gt;</definition>
    </FE>
    <frameRelation type="Inherits from">
        <relatedFrame>State_of_entity</relatedFrame>
    </frameRelation>
    <frameRelation type="Is Inherited by"/>
    <frameRelation type="Perspective on"/>
    <frameRelation type="Is Perspectivized in"/>
    <frameRelation type="Uses">
        <relatedFrame>Emotions</relatedFrame>
    </frameRelation>
    <frameRelation type="Is Used by"/>
    <frameRelation type="Subframe of"/>
    <frameRelation type="Has Subframe(s)"/>
    <frameRelation type="Precedes"/>
    <frameRelation type="Is Preceded by"/>
    <frameRelation type="Is Inchoative of"/>
    <frameRelation type="Is Causative of"/>
    <frameRelation type="See also"/>
    <lexUnit status="Finished_Initial" POS="N" name="pickle.n" ID="5463" lemmaID="45598" cBy="669" cDate="04/09/2002 04:05:59 PDT Tue">
        <definition>COD: 2. a pickle informal a difficult situation. </definition>
        <sentenceCount annotated="9" total="44"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="pickle"/>
    </lexUnit>
    <lexUnit status="Finished_Initial" POS="N" name="scrape.n" ID="5464" lemmaID="34534" cBy="669" cDate="04/09/2002 04:08:41 PDT Tue">
        <definition>COD: an embarrassing or difficult predicament. </definition>
        <sentenceCount annotated="4" total="56"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="scrape"/>
    </lexUnit>
    <lexUnit status="Needs_SCs" POS="N" name="pinch.n" ID="5465" lemmaID="45600" cBy="669" cDate="04/09/2002 04:21:27 PDT Tue">
        <definition>FN: a difficult situation</definition>
        <sentenceCount annotated="0" total="51"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="pinch"/>
    </lexUnit>
    <lexUnit status="Finished_Initial" POS="N" name="predicament.n" ID="5466" lemmaID="45601" cBy="669" cDate="04/09/2002 04:25:44 PDT Tue">
        <definition>COD: a difficult situation. </definition>
        <sentenceCount annotated="5" total="83"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="predicament"/>
    </lexUnit>
    <lexUnit status="Finished_Initial" POS="N" name="bind.n" ID="5467" lemmaID="3610" cBy="669" cDate="04/10/2002 10:05:07 PDT Wed">
        <definition>COD: a problematical situation.</definition>
        <sentenceCount annotated="5" total="49"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="bind"/>
    </lexUnit>
    <lexUnit status="Finished_Initial" POS="N" name="fix.n" ID="5468" lemmaID="45604" cBy="669" cDate="04/10/2002 10:08:31 PDT Wed">
        <definition>COD: in sing. informal a difficult or awkward situation.                                          How on earth did you get into such a fix?</definition>
        <sentenceCount annotated="5" total="66"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="fix"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="jam.n" ID="5469" lemmaID="45605" cBy="669" cDate="04/10/2002 10:12:08 PDT Wed">
        <definition>COD: informal an awkward situation or predicament:                                            I'm in a jam.</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="jam"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="mess.n" ID="5470" lemmaID="45606" cBy="669" cDate="04/10/2002 10:14:42 PDT Wed">
        <definition>COD: a confused and problematic situation. </definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="mess"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="plight.n" ID="7354" lemmaID="29396" cBy="664" cDate="09/03/2002 03:28:32 PDT Tue">
        <definition>COD: a dangerous, difficult, or otherwise unfortunate situation. </definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="plight"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="misfortune.n" ID="7355" lemmaID="24512" cBy="664" cDate="09/03/2002 03:29:22 PDT Tue">
        <definition>COD: an unfortunate event. </definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="misfortune"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="problem.n" ID="7356" lemmaID="30533" cBy="664" cDate="09/03/2002 03:29:41 PDT Tue">
        <definition>COD: an unwelcome or harmful matter needing to be dealt with and overcome. </definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="problem"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="trouble.n" ID="7357" lemmaID="41335" cBy="664" cDate="09/03/2002 03:29:51 PDT Tue">
        <definition>COD: difficulty or problems. </definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="trouble"/>
    </lexUnit>
</frame>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/frame/Economy.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="frame.xsl"?>
<frame cBy="618" cDate="07/18/2005 04:05:13 PDT Mon" name="Economy" ID="1572" xsi:schemaLocation="../schema/frame.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <definition>&lt;def-root&gt;A &lt;fen&gt;Political_region&lt;/fen&gt;, often a nation,  has an economic system, the&lt;fen&gt;Economy&lt;/fen&gt;, defined by the level of production and consumption of goods and services.  The &lt;fen&gt;Market_type&lt;/fen&gt; or &lt;fen&gt;Domain&lt;/fen&gt; may be specified.

&lt;ex&gt;The &lt;fex name="pol"&gt;Canadian&lt;/fex&gt; &lt;t&gt;&lt;fex name="Economy"&gt;economy&lt;/fex&gt;&lt;/t&gt; will continue to expand in 2005.&lt;/ex&gt;
&lt;ex&gt;Medical industry is a new force in the &lt;fex name="dom"&gt;industrial&lt;/fex&gt; &lt;t&gt;&lt;fex name="Economy"&gt;economy&lt;/fex&gt;&lt;/t&gt; &lt;fex name="pol"&gt;of Lin'an&lt;/fex&gt;.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    <FE bgColor="0000FF" fgColor="FFFFFF" coreType="Core" cBy="618" cDate="07/18/2005 04:15:48 PDT Mon" abbrev="pol" name="Political_region" ID="8602">
        <definition>&lt;def-root&gt;The &lt;fen&gt;Political_region&lt;/fen&gt; is the nation, state, or other political body within which an economic system exists.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="800080" fgColor="FFFFFF" coreType="Core" cBy="618" cDate="07/18/2005 04:16:41 PDT Mon" abbrev="eco" name="Economy" ID="8603">
        <definition>&lt;def-root&gt;The &lt;fen&gt;Economy&lt;/fen&gt; is the state of the &lt;fen&gt;Political_region&lt;/fen&gt; as defined by the production, consumption, etc. of goods and services.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="FF0000" fgColor="FFFFFF" coreType="Peripheral" cBy="618" cDate="07/18/2005 04:23:02 PDT Mon" abbrev="dom" name="Domain" ID="8604">
        <definition>&lt;def-root&gt;The &lt;fen&gt;Domain&lt;/fen&gt; of the state for which the &lt;fen&gt;Economy&lt;/fen&gt; is being considered.

&lt;ex&gt;In this way the &lt;fex name="dom"&gt;agrarian&lt;/fex&gt; &lt;t&gt;economy&lt;/t&gt; of the mainland might have proceeded towards a further specialization in agricultural products and a more effective production of food.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="A52A2A" fgColor="FFFFFF" coreType="Peripheral" cBy="618" cDate="07/18/2005 04:25:05 PDT Mon" abbrev="mar" name="Market_type" ID="8605">
        <definition>&lt;def-root&gt;The type of economic market in which the &lt;fen&gt;Economy&lt;/fen&gt; exists.

&lt;ex&gt;For much of its post-1947 history, India ran a &lt;fex name="mar"&gt;socialist&lt;/fex&gt; &lt;t&gt;economy&lt;/t&gt;.&lt;/ex&gt;
&lt;ex&gt;China's &lt;fex name="mar"&gt;free-market&lt;/fex&gt; &lt;t&gt;economy&lt;/t&gt; is generating unprecedented but not unlimited press freedoms, and there's momentum.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="2E8B57" fgColor="FFFFFF" coreType="Peripheral" cBy="618" cDate="07/18/2005 04:28:24 PDT Mon" abbrev="des" name="Descriptor" ID="8606">
        <definition>&lt;def-root&gt;A further depction of the &lt;fen&gt;Economy&lt;/fen&gt;.

&lt;ex&gt;Hertfordshire enjoys a &lt;fex name="des"&gt;buoyant&lt;/fex&gt; &lt;t&gt;economy&lt;/t&gt;.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <frameRelation type="Inherits from"/>
    <frameRelation type="Is Inherited by"/>
    <frameRelation type="Perspective on"/>
    <frameRelation type="Is Perspectivized in"/>
    <frameRelation type="Uses">
        <relatedFrame>Political_locales</relatedFrame>
    </frameRelation>
    <frameRelation type="Is Used by"/>
    <frameRelation type="Subframe of"/>
    <frameRelation type="Has Subframe(s)"/>
    <frameRelation type="Precedes"/>
    <frameRelation type="Is Preceded by"/>
    <frameRelation type="Is Inchoative of"/>
    <frameRelation type="Is Causative of"/>
    <frameRelation type="See also"/>
    <lexUnit status="Finished_Initial" POS="N" name="economy.n" ID="12489" lemmaID="12193" cBy="618" cDate="07/18/2005 04:10:36 PDT Mon">
        <definition>COD: the state of a country or region in terms of the production and consumption of goods and services and the supply of money.</definition>
        <sentenceCount annotated="20" total="206"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="economy"/>
    </lexUnit>
    <lexUnit status="New" POS="A" name="economic.a" ID="12490" lemmaID="12187" cBy="618" cDate="07/18/2005 04:15:20 PDT Mon">
        <definition>COD: of or relating to economics or the economy.</definition>
        <sentenceCount annotated="0" total="141"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="A" name="economic"/>
    </lexUnit>
</frame>
