=== FabianFriedrich/Text2Process/resources/fndata-1.5/schema/frame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:fn="http://framenet.icsi.berkeley.edu"
            targetNamespace="http://framenet.icsi.berkeley.edu"
            xmlns="http://framenet.icsi.berkeley.edu"
            elementFormDefault="qualified">
<!-- 
    1. Root element is 'frame'
    2. 'frame' has 3 attributes:
        1. 'ID', a nonNegativeInteger
        2. 'name' a word (that could contain underscores/dashes etc.) starting with a capital letter
        3. 'cDate' dayabbr monthabbr daynum hour:min:sec timezone year
    3. 'frame' has 3 elements:
        1. 'definition' a string
        2. 'fe'a complex type described below (1+)
        3. 'lexUnit' a complex type described below (0+)
    3.2.1 'fe' has 7 attributes:
        1. 'ID' (same as above description)
        2. 'name' (same as above description)
        3. 'abbrev' (same type as 'name')
        4. 'cDate' (same as above description)
        5. 'coreType' (same type as 'name')
        6. 'fgColor' (a word (lowercase) indicating a color)
        7. 'bgColor' (same type as 'fgColor')
    3.2.2 'fe' has 2 elements:
        1. 'definition' (a string)
        2. 'semType' (just as two attributes 'ID' and 'name') (implied 0+)
    3.3.1 'lexUnit' has 6 attributes:
        1. 'ID' (same as above description)
        2. 'name' (word with a period followed by a letter)
        3. 'POS' (a capital letter)
        4. 'status' (capital letter word)
        5. 'cDate' (same as above)
        6. 'lemmaId' (a nonNegativeInteger)
    3.3.2 'lexUnit' has 4 elements
        1. 'definition' (has SOURCE then a colon followed by a string)
        2. 'annotation' (has 2 elements, 'annotated' and 'total' both nonNegativeIntegers)
        3. 'lexeme' (a complex type described below) (1+)
        4. 'semType' (same as above) (implied 0+)
    3.3.2.3.1 'lexeme' has 4 attributes
        1. 'ID' (same)
        2. 'POS' (a capital letter)
        3. 'breakBefore' (a boolean)
        4. 'headWord' (a boolean)
    3.3.2.3.2 'lexeme' has text
-->
    <xsd:include schemaLocation="commonTypes.xsd"/>
    <xsd:element name="frame">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="definition" type="xsd:string"/>
                <xsd:element name="semType" type="fn:semTypeRefType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="FE" type="fn:FEType" maxOccurs="unbounded"/>
                <xsd:element name="FEcoreSet" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="memberFE" type="fn:internalFrameRelationFEType" minOccurs="2" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="frameRelation" type="fn:relatedFramesType"
                    maxOccurs="unbounded"/>
                <xsd:element name="lexUnit" type="fn:frameLUType" 
                    minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="ID" type="fn:IDType" use="required"/>
            <xsd:attribute name="name" type="fn:frameNameType" use="required"/>
            <xsd:attribute name="cDate" type="fn:dateTimeType" use="required"/>
            <xsd:attribute name="cBy" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element> <!-- end 'frame' -->

    <!-- FE Type -->
    <xsd:complexType name="FEType">
        <xsd:sequence>
            <xsd:element name="definition" type="xsd:string"/>
            <xsd:element name="semType" type="fn:semTypeRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="requiresFE" type="fn:internalFrameRelationFEType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="excludesFE" type="fn:internalFrameRelationFEType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="ID" type="fn:IDType" use="required"/>
        <xsd:attribute name="name" type="fn:frameNameType" use="required"/>
        <xsd:attribute name="abbrev" type="xsd:string" use="required"/>
        <xsd:attribute name="cDate" type="fn:dateTimeType" use="required"/>
        <xsd:attribute name="cBy" type="xsd:string" use="required"/>
        <xsd:attribute name="coreType" type="fn:coreType" use="required"/>
        <xsd:attribute name="fgColor" type="fn:RGBColorType" use="required"/>
        <xsd:attribute name="bgColor" type="fn:RGBColorType" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="internalFrameRelationFEType">
        <xsd:attribute name="ID" type="xsd:int" use="required"/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <!-- Related frames type -->
    <xsd:complexType name="relatedFramesType">
        <xsd:sequence>
            <xsd:element name="relatedFrame" type="fn:frameNameType"
                minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <!-- frame-embedded lexUnit type -->
    <xsd:complexType name="frameLUType">
        <xsd:sequence>
            <xsd:element name="definition" type="fn:defType"/>
            <xsd:element name="sentenceCount">
                <xsd:complexType>
                    <xsd:attribute name="total" type="fn:countType" use="required"/>
                    <xsd:attribute name="annotated" type="fn:countType" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="lexeme" type="fn:lexemeType" maxOccurs="unbounded"/>
            <xsd:element name="semType" type="fn:semTypeRefType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attributeGroup ref="fn:basicLUAttributes"/>
        <xsd:attribute name="cDate" type="fn:dateTimeType" use="required"/>
        <xsd:attribute name="cBy" type="xsd:string" use="required"/>
        <xsd:attribute name="lemmaID" type="fn:IDType" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/frame/Noise_makers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="frame.xsl"?>
<frame cBy="605" cDate="03/05/2004 04:05:16 PST Fri" name="Noise_makers" ID="1017" xsi:schemaLocation="../schema/frame.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <definition>&lt;def-root&gt;The &lt;fen&gt;Noise_maker&lt;/fen&gt; is an artifact used to produce sound, especially for musical effect.

&lt;ex&gt;The &lt;fex name="Grnd"&gt;church&lt;/fex&gt; &lt;t&gt;&lt;fex name="nm"&gt;bells&lt;/fex&gt;&lt;/t&gt; rang&lt;/ex&gt;
&lt;ex&gt;The &lt;fex name="Grnd"&gt;car&lt;/fex&gt; &lt;t&gt;&lt;fex name="nm"&gt;alarm&lt;/fex&gt;&lt;/t&gt; went off again&lt;/ex&gt;
&lt;ex&gt;I have never played an &lt;fex name="tp"&gt;acoustic&lt;/fex&gt;  &lt;t&gt;&lt;fex name="nm"&gt;guitar&lt;/fex&gt;&lt;/t&gt;.&lt;/ex&gt;
&lt;ex&gt;Each artist personally owns a Steinway and has chosen to perform on the &lt;fex name="Creator"&gt;Steinway&lt;/fex&gt; &lt;t&gt;piano&lt;/t&gt; professionally&lt;/ex&gt;&lt;/def-root&gt;</definition>
    <FE bgColor="FF0000" fgColor="FFFFFF" coreType="Core" cBy="605" cDate="03/05/2004 04:05:16 PST Fri" abbrev="nm" name="Noise_maker" ID="6043">
        <definition>&lt;def-root&gt;This FE identifies the entity or substance that is designed to produce sound.&lt;/def-root&gt;</definition>
        <semType name="Artifact" ID="61"/>
    </FE>
    <FE bgColor="9400D3" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:05:16 PST Fri" abbrev="s" name="Use" ID="6044">
        <definition>&lt;def-root&gt;The use for which an &lt;fen&gt;Noise_maker&lt;/fen&gt;  is intended.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="00BFFF" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:05:17 PST Fri" abbrev="crt" name="Creator" ID="6045">
        <definition>&lt;def-root&gt;An individual or individuals that bring the &lt;fen&gt;Noise_maker&lt;/fen&gt; into existence.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="FFA500" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:05:17 PST Fri" abbrev="toc" name="Time_of_creation" ID="6046">
        <definition>&lt;def-root&gt;The time at which a &lt;fen&gt;Noise_maker&lt;/fen&gt; comes into existence.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="008000" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:05:17 PST Fri" abbrev="" name="Name" ID="6047">
        <definition>&lt;def-root&gt;The term used to refer to an &lt;fen&gt;Noise_maker&lt;/fen&gt;.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="00008B" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:05:17 PST Fri" abbrev="tp" name="Type" ID="6048">
        <definition>&lt;def-root&gt;An indication of the subtype of &lt;fen&gt;Noise_maker&lt;/fen&gt;.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="A52A2A" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:05:17 PST Fri" abbrev="mat" name="Material" ID="6049">
        <definition>&lt;def-root&gt;Any indication of what makes up the &lt;fen&gt;Noise_maker&lt;/fen&gt;, including components, etc.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="7CCD7C" fgColor="FFFFFF" coreType="Peripheral" cBy="605" cDate="03/05/2004 04:19:06 PST Fri" abbrev="Grnd" name="Ground" ID="6050">
        <definition>&lt;def-root&gt;The location with which the &lt;fen&gt;Noise_maker&lt;/fen&gt; is associated.&lt;/def-root&gt;</definition>
    </FE>
    <frameRelation type="Inherits from">
        <relatedFrame>Artifact</relatedFrame>
    </frameRelation>
    <frameRelation type="Is Inherited by"/>
    <frameRelation type="Perspective on"/>
    <frameRelation type="Is Perspectivized in"/>
    <frameRelation type="Uses"/>
    <frameRelation type="Is Used by"/>
    <frameRelation type="Subframe of"/>
    <frameRelation type="Has Subframe(s)"/>
    <frameRelation type="Precedes"/>
    <frameRelation type="Is Preceded by"/>
    <frameRelation type="Is Inchoative of"/>
    <frameRelation type="Is Causative of"/>
    <frameRelation type="See also"/>
    <lexUnit status="Created" POS="N" name="guitar.n" ID="10210" lemmaID="17047" cBy="605" cDate="03/05/2004 04:31:24 PST Fri">
        <definition>COD: a stringed musical instrument with a fretted fingerboard and six or twelve strings, played by plucking or strumming with the fingers or a plectrum</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="guitar"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="bell.n" ID="10211" lemmaID="3298" cBy="605" cDate="03/05/2004 04:32:09 PST Fri">
        <definition>COD: a hollow object, typically made of metal and in the shape of a deep inverted cup, that sounds a clear musical note when struck</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="bell"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="siren.n" ID="10212" lemmaID="36040" cBy="605" cDate="03/05/2004 04:32:49 PST Fri">
        <definition>COD: a device that makes a loud prolonged signal or warning sound</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="siren"/>
    </lexUnit>
    <lexUnit status="Needs_SCs" POS="N" name="piano.n" ID="10213" lemmaID="28875" cBy="605" cDate="03/05/2004 04:33:21 PST Fri">
        <definition>COD: a large keyboard musical instrument with a wooden case enclosing a soundboard and metal strings, which are struck by hammers when the keys are depressed.</definition>
        <sentenceCount annotated="1" total="90"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="piano"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="rattle.n" ID="10214" lemmaID="31896" cBy="605" cDate="03/05/2004 04:33:48 PST Fri">
        <definition>COD: a thing that makes a rattling sound, in particular a baby's toy consisting of a container filled with small pellets</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="rattle"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="xylophone.n" ID="10215" lemmaID="44636" cBy="605" cDate="03/05/2004 04:34:28 PST Fri">
        <definition>COD: a musical instrument played by striking a row of wooden bars of graduated length with small beaters</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="xylophone"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="drum.n" ID="10216" lemmaID="11855" cBy="605" cDate="03/05/2004 04:35:00 PST Fri">
        <definition>COD: a percussion instrument sounded by being struck with sticks or the hands, typically cylindrical, barrel-shaped, or bowl-shaped with a taut membrane over one or both ends.</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="drum"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="cello.n" ID="10217" lemmaID="5868" cBy="605" cDate="03/05/2004 04:35:48 PST Fri">
        <definition>COD:  a bass instrument of the violin family, held upright on the floor between the legs of the seated player.</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="cello"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="saxophone.n" ID="10218" lemmaID="34273" cBy="605" cDate="03/05/2004 04:38:50 PST Fri">
        <definition>COD: a member of a family of metal wind instruments with a reed like a clarinet, used especially in jazz and dance music</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="saxophone"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="alarm.n" ID="11243" lemmaID="945" cBy="303" cDate="11/19/2004 04:52:12 PST Fri">
        <definition>COD: a warning sound or device.</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="alarm"/>
    </lexUnit>
</frame>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/frame/Infrastructure.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="frame.xsl"?>
<frame cBy="618" cDate="06/02/2005 05:21:14 PDT Thu" name="Infrastructure" ID="1481" xsi:schemaLocation="../schema/frame.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <definition>&lt;def-root&gt;A group of entities exist (as an infrastructure) such that a particular type of &lt;fen&gt;Activity&lt;/fen&gt; is either enabled or facilitated.  The entities may or may not have been organized specifically for the &lt;fen&gt;Activity&lt;/fen&gt;.  The infrastructure is constituted by &lt;fen&gt;Resource&lt;/fen&gt;s that can be made use of by &lt;fen&gt;User&lt;/fen&gt;s, and the infrastructure may be specified for its &lt;fen&gt;Place&lt;/fen&gt; or &lt;fen&gt;Possessor&lt;/fen&gt;.

&lt;ex&gt;While the &lt;fex name="Possessor"&gt;US&lt;/fex&gt; &lt;fex name="Activity"&gt;transportation&lt;/fex&gt; &lt;t&gt;&lt;fex name="Infrastructure"&gt;infrastructure&lt;/fex&gt;&lt;/t&gt; continues to crumble, competitors in Brazil and Argentina are investing millions to improve their transportation&lt;/ex&gt;

&lt;ex&gt;The exacerbated sprawl like growth in the last decades has been a direct result of decisions taken in the creation, boost, and development of &lt;fex name="Resource"&gt;highway&lt;/fex&gt; &lt;t&gt;&lt;fex name="Infrastructure"&gt;infrastructure&lt;/fex&gt;&lt;/t&gt;.&lt;/ex&gt;

&lt;ex&gt;Mexico's Ministry of Tourism expects to see more than $1.78 billion invested to further develop &lt;fex name="Possessor"&gt;the country's&lt;/fex&gt; &lt;fex name="Activity"&gt;tourism&lt;/fex&gt; &lt;t&gt;&lt;fex name="Infrastructure"&gt;infrastructure&lt;/fex&gt;&lt;/t&gt;.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    <FE bgColor="A52A2A" fgColor="FFFFFF" coreType="Core" cBy="618" cDate="06/02/2005 05:58:37 PDT Thu" abbrev="act" name="Activity" ID="8074">
        <definition>&lt;def-root&gt;The &lt;fen&gt;Activity&lt;/fen&gt; which is enabled or facilitated by the infrastructure.

&lt;ex&gt;At present, you'll find that Belize has a &lt;fex name="act"&gt;travel&lt;/fex&gt; &lt;t&gt;infrastructure&lt;/t&gt; that's improving but still far from polished.&lt;/ex&gt;
&lt;ex&gt;As a result , one of the central policy priorities of government has been to strengthen significantly the
&lt;fex name="act"&gt;academic&lt;/fex&gt; &lt;t&gt;infrastructure&lt;/t&gt;.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="008000" fgColor="FFFFFF" coreType="Peripheral" cBy="618" cDate="06/02/2005 06:11:07 PDT Thu" abbrev="pla" name="Place" ID="8075">
        <definition>&lt;def-root&gt;The location of the infrastructure.

&lt;ex&gt;Much of the transportation &lt;t&gt;infrastructure&lt;/t&gt; &lt;fex name="Place"&gt;in the US&lt;/fex&gt; was developed when there was no need for private money.&lt;/ex&gt;&lt;/def-root&gt;</definition>
        <semType name="Locative_relation" ID="182"/>
    </FE>
    <FE bgColor="FF0000" fgColor="FFFFFF" coreType="Core" cBy="618" cDate="06/02/2005 06:12:54 PDT Thu" abbrev="pos" name="Possessor" ID="8076">
        <definition>&lt;def-root&gt;The organization, institution, or individual who owns the infrastructure.

&lt;ex&gt;Increase the value of  &lt;fex name="pos"&gt;your company's&lt;/fex&gt; technology &lt;t&gt;infrastructure&lt;/t&gt;&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="0000FF" fgColor="FFFFFF" coreType="Core" cBy="618" cDate="06/02/2005 06:16:45 PDT Thu" abbrev="res" name="Resource" ID="8077">
        <definition>&lt;def-root&gt;The infrastructure may be conceived of as consisting of Resources that can be made use of by Users in performing an Activity.

&lt;ex&gt;Members of the organization can use the &lt;fex name="res"&gt;service&lt;/fex&gt; &lt;t&gt;infrastructure&lt;/t&gt; to perform management tasks.&lt;/ex&gt;
&lt;ex&gt;It is critical to point out that, while our &lt;fex name="res"&gt;highway&lt;/fex&gt; &lt;t&gt;infrastructure&lt;/t&gt; continues to deteriorate, highway use is on the rise.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="800080" fgColor="FFFFFF" coreType="Core" cBy="618" cDate="06/02/2005 06:27:16 PDT Thu" abbrev="user" name="User" ID="8078">
        <definition>&lt;def-root&gt;The people for whom the infrastructure is designed to be used by.  In the cases where the constituent denoting the user also evokes the &lt;fen&gt;Activity&lt;/fen&gt;, we annotate this on the second FE layer.

&lt;ex&gt; There are no specific barriers to investment in Bulgaria's &lt;fex name="user"&gt;tourist&lt;/fex&gt; &lt;t&gt;infrastructure&lt;/t&gt; or in the import of products to be used for tourist infrastructure development.&lt;/ex&gt;
&lt;ex&gt; There are no specific barriers to investment in Bulgaria's &lt;fex name="act"&gt;tourist&lt;/fex&gt; &lt;t&gt;infrastructure&lt;/t&gt; or in the import of products to be used for tourist infrastructure development.&lt;/ex&gt;
&lt;ex&gt;Our company makes constant use of the vast &lt;t&gt;infrastructure&lt;/t&gt; &lt;fex name="user"&gt;for businesses&lt;/fex&gt; offered by the government.&lt;/ex&gt;&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="FF00FF" fgColor="FFFFFF" coreType="Peripheral" cBy="618" cDate="06/02/2005 06:34:25 PDT Thu" abbrev="des" name="Descriptor" ID="8079">
        <definition>&lt;def-root&gt;A characterization of the infrastructure.&lt;/def-root&gt;</definition>
    </FE>
    <FE bgColor="00008B" fgColor="FFFFFF" coreType="Core" cBy="664" cDate="12/07/2005 11:56:02 PST Wed" abbrev="inf" name="Infrastructure" ID="9589">
        <definition>&lt;def-root&gt;The collection of entities and/or institutions that help to promote an &lt;fen&gt;Activity&lt;/fen&gt; of a public character.&lt;/def-root&gt;</definition>
    </FE>
    <frameRelation type="Inherits from">
        <relatedFrame>Artifact</relatedFrame>
    </frameRelation>
    <frameRelation type="Is Inherited by"/>
    <frameRelation type="Perspective on"/>
    <frameRelation type="Is Perspectivized in"/>
    <frameRelation type="Uses"/>
    <frameRelation type="Is Used by">
        <relatedFrame>Institutions</relatedFrame>
    </frameRelation>
    <frameRelation type="Subframe of"/>
    <frameRelation type="Has Subframe(s)"/>
    <frameRelation type="Precedes"/>
    <frameRelation type="Is Preceded by"/>
    <frameRelation type="Is Inchoative of"/>
    <frameRelation type="Is Causative of"/>
    <frameRelation type="See also"/>
    <lexUnit status="Finished_Initial" POS="N" name="infrastructure.n" ID="12168" lemmaID="19903" cBy="618" cDate="06/02/2005 06:38:48 PDT Thu">
        <definition>FN: the basic facilities, installations, or other components needed for the operation of a system or organization</definition>
        <sentenceCount annotated="44" total="440"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="infrastructure"/>
    </lexUnit>
    <lexUnit status="Created" POS="N" name="base.n" ID="12206" lemmaID="2969" cBy="618" cDate="06/13/2005 04:45:20 PDT Mon">
        <definition>FN: a system that allows for a particular activity to take place.</definition>
        <sentenceCount annotated="0" total="0"/>
        <lexeme order="1" headword="false" breakBefore="false" POS="N" name="base"/>
    </lexUnit>
</frame>
