=== FabianFriedrich/Text2Process/resources/fndata-1.5/schema/lexUnit.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : lexUnit.xsd
    Created on : July 25, 2007, 11:30 PM
    Author     : jhong
    Description:
        FrameNet LexUnit XML format which incorporates both valence information
        and annotation.  This format was adopted as of R1.4.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:fn="http://framenet.icsi.berkeley.edu"
            targetNamespace="http://framenet.icsi.berkeley.edu"
            xmlns="http://framenet.icsi.berkeley.edu"
            elementFormDefault="qualified">
    
    <!-- 
       A sketch of the XML under the root is as follows:
       
       <lexUnit ...>
         <header> ... </header>
         <definition> ... </definition>
         <lexeme />+
         <semType />+
         <valences> ... </valences>
         <subCorpus> ... </subCorpus>*
       </lexUnit>

    -->
    <xsd:include schemaLocation="commonTypes.xsd"/>
    <xsd:include schemaLocation="header.xsd"/>
    <xsd:include schemaLocation="sentence.xsd"/>

    <!-- ***************  Schema for the root node  ****************** -->
    <xsd:element name="lexUnit">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="header" type="fn:headerType"
                        minOccurs="1" maxOccurs="1"/>
                <xsd:element name="definition" type="fn:defType"
                        maxOccurs="1"/>
                <xsd:element name="lexeme" type="fn:lexemeType"
                        minOccurs="1" maxOccurs="unbounded"/>
                <xsd:element name="semType" type="fn:semTypeRefType"
                        minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="valences" type="fn:valencesType"
                        minOccurs="0" maxOccurs="1"/>
                <xsd:element name="subCorpus" type="fn:subCorpusType"
                         minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="fn:basicLUAttributes"/>
            <xsd:attributeGroup ref="fn:frameReference"/>
            <xsd:attribute name="totalAnnotated" type="fn:countType"/>
        </xsd:complexType>
    </xsd:element>
    
    <!-- ************* Types Contained in the Root Node **************  -->
    
    <!-- valences type -->
    <xsd:complexType name="valencesType">
        <xsd:sequence>
            <xsd:element name="governor" type="fn:governorType"
                minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="FERealization" type="fn:FERealizationType"
                minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="FEGroupRealization" type="fn:FEGroupRealizationType"
                minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- subCorpus element type -->
    <xsd:complexType name="subCorpusType">
        <xsd:sequence>
            <xsd:element name="sentence" type="fn:sentenceType"
                         minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    
    <!-- ************* Types contains in the valences type ************** -->
    
    <!-- governor type -->
    <xsd:complexType name="governorType">
        <xsd:sequence>
            <xsd:element name="annoSet" type="fn:annoSetType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="lemma" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/> <!-- more strict type? -->
    </xsd:complexType>
    
    <!-- FERealization Type -->
    <xsd:complexType name="FERealizationType">
        <xsd:sequence>
            <xsd:element name="FE" type="fn:FEValenceType" maxOccurs="1"/>
            <xsd:element name="pattern" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="valenceUnit" type="fn:valenceUnitType"/>
                        <xsd:element name="annoSet" type="fn:annoSetType" maxOccurs="unbounded"/>
                    </xsd:sequence>
                    <xsd:attribute name="total" type="fn:countType" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="total" type="fn:countType" use="required"/>
    </xsd:complexType>
  
    <!-- FEGRoupRealization type -->
    <xsd:complexType name="FEGroupRealizationType">
        <xsd:sequence>
            <xsd:element name="FE" type="fn:FEValenceType" maxOccurs="unbounded"/>
            <xsd:element name="pattern" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="valenceUnit" type="fn:valenceUnitType" maxOccurs="unbounded"/>
                        <xsd:element name="annoSet" type="fn:annoSetType" maxOccurs="unbounded"/>
                    </xsd:sequence>
                    <xsd:attribute name="total" type="fn:countType" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="total" type="fn:countType" use="required"/>
    </xsd:complexType>
    

    <!-- Attributes-only Complex Types used in valences -->
    <xsd:complexType name="annoSetType">
        <xsd:attribute name="ID" type="fn:IDType" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="FEValenceType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="valenceUnitType">
        <xsd:attribute name="FE" type="xsd:string" use="required"/>
        <xsd:attribute name="PT" type="xsd:string" use="required"/>
        <xsd:attribute name="GF" type="xsd:string" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu14976.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="ADV" name="speedily.adv" ID="14976" frame="Speed" frameID="966" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="1E90FF" type="Core" abbrev="Att" name="Attribute"/>
            <FE fgColor="FFFFFF" bgColor="A52A2A" type="Extra-Thematic" abbrev="Cir" name="Circumstances"/>
            <FE fgColor="FFFFFF" bgColor="FF00FF" type="Core" abbrev="Deg" name="Degree"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="Ent" name="Entity"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Extra-Thematic" abbrev="Exp" name="Explanation"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Core" abbrev="Spe" name="Speed"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Extra-Thematic" abbrev="Tim" name="Time"/>
        </frame>
    </header>
    <definition>FN: in a rapid manner</definition>
    <lexeme POS="ADV" name="speedily"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu14414.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="PREP" name="from_to.prep" ID="14414" frame="Delimitation_of_diversity" frameID="1680" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="FF69B4" type="Peripheral" abbrev="deg" name="Degree"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="Item" name="Item"/>
            <FE fgColor="FFFFFF" bgColor="006400" type="Core" abbrev="Low" name="Limit1"/>
            <FE fgColor="FFFFFF" bgColor="00BFFF" type="Core" abbrev="Upp" name="Limit2"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Core" abbrev="Val" name="Limits"/>
            <FE fgColor="FFFFFF" bgColor="9400D3" type="Core" abbrev="Var" name="Variable"/>
        </frame>
    </header>
    <definition>FN: indicating extreme points of a range.</definition>
    <lexeme order="1" headword="true" breakBefore="false" POS="PREP" name="from"/>
    <lexeme order="2" headword="false" breakBefore="true" POS="PREP" name="to"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu11652.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="A" name="next generation.a" ID="11652" frame="Stage_of_progress" frameID="1341" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="800080" type="Peripheral" abbrev="deg" name="Degree"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Peripheral" abbrev="dom" name="Domain"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="ent" name="Entity"/>
            <FE fgColor="FFFFFF" bgColor="FF00FF" type="Peripheral" abbrev="man" name="Manner"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Peripheral" abbrev="tim" name="Time"/>
        </frame>
    </header>
    <definition>FN: belonging  to the next stage of advancement</definition>
    <lexeme order="1" headword="false" breakBefore="false" POS="A" name="next"/>
    <lexeme order="2" headword="true" breakBefore="false" POS="N" name="generation"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu15638.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="V" name="expend.v" ID="15638" frame="Exhaust_resource" frameID="2220" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="age" name="Agent"/>
            <FE fgColor="FFFFFF" bgColor="FF69B4" type="Peripheral" abbrev="man" name="Manner"/>
            <FE fgColor="FFFFFF" bgColor="FF00FF" type="Peripheral" abbrev="mea" name="Means"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Peripheral" abbrev="pla" name="Place"/>
            <FE fgColor="FFFFFF" bgColor="800080" type="Peripheral" abbrev="pur" name="Purpose"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="res" name="Resource"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Peripheral" abbrev="tim" name="Time"/>
        </frame>
    </header>
    <definition>FN: use up.</definition>
    <lexeme POS="V" name="expend"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu13651.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="N" name="fury.n" ID="13651" frame="Emotion_directed" frameID="46" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="00BFFF" type="Extra-Thematic" abbrev="cir" name="Circumstances"/>
            <FE fgColor="FFFFFF" bgColor="FF69B4" type="Peripheral" abbrev="Degr" name="Degree"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Extra-Thematic" abbrev="ET" name="Empathy_target"/>
            <FE fgColor="FFFFFF" bgColor="A52A2A" type="Core" abbrev="Event" name="Event"/>
            <FE fgColor="FFFFFF" bgColor="800080" type="Core" abbrev="Exp" name="Experiencer"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Core" abbrev="Exr" name="Expressor"/>
            <FE fgColor="000000" bgColor="7FFF00" type="Extra-Thematic" abbrev="" name="Frequency"/>
            <FE fgColor="FFFFFF" bgColor="FF00FF" type="Peripheral" abbrev="" name="Manner"/>
            <FE fgColor="FFFFFF" bgColor="2E8B57" type="Peripheral" abbrev="" name="Parameter"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Extra-Thematic" abbrev="Reas" name="Reason"/>
            <FE fgColor="FFFFFF" bgColor="9F79EE" type="Core" abbrev="State" name="State"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="Stim" name="Stimulus"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Core" abbrev="Top" name="Topic"/>
        </frame>
    </header>
    <definition>COD: extreme anger.</definition>
    <lexeme POS="N" name="fury"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu10025.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="A" name="situated.a" ID="10025" frame="Being_located" frameID="960" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="000000" bgColor="9F79EE" type="Extra-Thematic" abbrev="" name="Cotheme"/>
            <FE fgColor="FFFFFF" bgColor="800080" type="Extra-Thematic" abbrev="Dep" name="Dependent_state"/>
            <FE fgColor="FFFFFF" bgColor="A9A9A9" type="Core" abbrev="" name="Location"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Peripheral" abbrev="" name="Place"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="" name="Theme"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Peripheral" abbrev="" name="Time"/>
        </frame>
    </header>
    <definition>FN: located in a place.</definition>
    <lexeme POS="A" name="situated"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu11707.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="V" name="disseminate.v" ID="11707" frame="Dispersal" frameID="267" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="Agent" name="Agent"/>
            <FE fgColor="FFFFFF" bgColor="2E8B57" type="Core" abbrev="" name="Cause"/>
            <FE fgColor="FFFFFF" bgColor="808080" type="Peripheral" abbrev="dis" name="Distance"/>
            <FE fgColor="FFFFFF" bgColor="800080" type="Peripheral" abbrev="Goal_a" name="Goal_area"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="Ind" name="Individuals"/>
            <FE fgColor="FFFFFF" bgColor="FF69B4" type="Peripheral" abbrev="" name="Manner"/>
            <FE fgColor="FFFFFF" bgColor="A52A2A" type="Peripheral" abbrev="" name="Means"/>
            <FE fgColor="FFFFFF" bgColor="00BFFF" type="Peripheral" abbrev="" name="Path"/>
            <FE fgColor="FFFFFF" bgColor="1E90FF" type="Peripheral" abbrev="" name="Place"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Extra-Thematic" abbrev="" name="Reason"/>
            <FE fgColor="0000FF" bgColor="d0d0d0" type="Extra-Thematic" abbrev="" name="Result"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Peripheral" abbrev="Src" name="Source"/>
            <FE fgColor="FFFFFF" bgColor="A9A9A9" type="Peripheral" abbrev="spe" name="Speed"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Peripheral" abbrev="" name="Time"/>
        </frame>
    </header>
    <definition>COD: spread widely</definition>
    <lexeme POS="V" name="disseminate"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu14199.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" incorporatedFE="Landmark_period" POS="N" name="nowadays.n" ID="14199" frame="Temporal_collocation" frameID="1895" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="800080" type="Extra-Thematic" abbrev="Eve" name="Event_description"/>
            <FE fgColor="FFFFFF" bgColor="90876C" type="Core" abbrev="LEn" name="Landmark_entity"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="LEv" name="Landmark_event"/>
            <FE fgColor="FFFFFF" bgColor="1E90FF" type="Core" abbrev="LPe" name="Landmark_period"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Core" abbrev="TEn" name="Trajector_entity"/>
            <FE fgColor="FFFFFF" bgColor="FF00FF" type="Core" abbrev="TEv" name="Trajector_event"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="TPe" name="Trajector_period"/>
        </frame>
    </header>
    <definition>COD: at the present time, in contrast with the past.</definition>
    <lexeme POS="N" name="nowadays"/>
    <valences/>
    <subCorpus name="other-unmatched-(1)"/>
</lexUnit>
