=== FabianFriedrich/Text2Process/resources/fndata-1.5/schema/lexUnit.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : lexUnit.xsd
    Created on : July 25, 2007, 11:30 PM
    Author     : jhong
    Description:
        FrameNet LexUnit XML format which incorporates both valence information
        and annotation.  This format was adopted as of R1.4.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:fn="http://framenet.icsi.berkeley.edu"
            targetNamespace="http://framenet.icsi.berkeley.edu"
            xmlns="http://framenet.icsi.berkeley.edu"
            elementFormDefault="qualified">
    
    <!-- 
       A sketch of the XML under the root is as follows:
       
       <lexUnit ...>
         <header> ... </header>
         <definition> ... </definition>
         <lexeme />+
         <semType />+
         <valences> ... </valences>
         <subCorpus> ... </subCorpus>*
       </lexUnit>

    -->
    <xsd:include schemaLocation="commonTypes.xsd"/>
    <xsd:include schemaLocation="header.xsd"/>
    <xsd:include schemaLocation="sentence.xsd"/>

    <!-- ***************  Schema for the root node  ****************** -->
    <xsd:element name="lexUnit">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="header" type="fn:headerType"
                        minOccurs="1" maxOccurs="1"/>
                <xsd:element name="definition" type="fn:defType"
                        maxOccurs="1"/>
                <xsd:element name="lexeme" type="fn:lexemeType"
                        minOccurs="1" maxOccurs="unbounded"/>
                <xsd:element name="semType" type="fn:semTypeRefType"
                        minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="valences" type="fn:valencesType"
                        minOccurs="0" maxOccurs="1"/>
                <xsd:element name="subCorpus" type="fn:subCorpusType"
                         minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="fn:basicLUAttributes"/>
            <xsd:attributeGroup ref="fn:frameReference"/>
            <xsd:attribute name="totalAnnotated" type="fn:countType"/>
        </xsd:complexType>
    </xsd:element>
    
    <!-- ************* Types Contained in the Root Node **************  -->
    
    <!-- valences type -->
    <xsd:complexType name="valencesType">
        <xsd:sequence>
            <xsd:element name="governor" type="fn:governorType"
                minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="FERealization" type="fn:FERealizationType"
                minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="FEGroupRealization" type="fn:FEGroupRealizationType"
                minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- subCorpus element type -->
    <xsd:complexType name="subCorpusType">
        <xsd:sequence>
            <xsd:element name="sentence" type="fn:sentenceType"
                         minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    
    <!-- ************* Types contains in the valences type ************** -->
    
    <!-- governor type -->
    <xsd:complexType name="governorType">
        <xsd:sequence>
            <xsd:element name="annoSet" type="fn:annoSetType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="lemma" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/> <!-- more strict type? -->
    </xsd:complexType>
    
    <!-- FERealization Type -->
    <xsd:complexType name="FERealizationType">
        <xsd:sequence>
            <xsd:element name="FE" type="fn:FEValenceType" maxOccurs="1"/>
            <xsd:element name="pattern" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="valenceUnit" type="fn:valenceUnitType"/>
                        <xsd:element name="annoSet" type="fn:annoSetType" maxOccurs="unbounded"/>
                    </xsd:sequence>
                    <xsd:attribute name="total" type="fn:countType" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="total" type="fn:countType" use="required"/>
    </xsd:complexType>
  
    <!-- FEGRoupRealization type -->
    <xsd:complexType name="FEGroupRealizationType">
        <xsd:sequence>
            <xsd:element name="FE" type="fn:FEValenceType" maxOccurs="unbounded"/>
            <xsd:element name="pattern" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="valenceUnit" type="fn:valenceUnitType" maxOccurs="unbounded"/>
                        <xsd:element name="annoSet" type="fn:annoSetType" maxOccurs="unbounded"/>
                    </xsd:sequence>
                    <xsd:attribute name="total" type="fn:countType" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="total" type="fn:countType" use="required"/>
    </xsd:complexType>
    

    <!-- Attributes-only Complex Types used in valences -->
    <xsd:complexType name="annoSetType">
        <xsd:attribute name="ID" type="fn:IDType" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="FEValenceType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="valenceUnitType">
        <xsd:attribute name="FE" type="xsd:string" use="required"/>
        <xsd:attribute name="PT" type="xsd:string" use="required"/>
        <xsd:attribute name="GF" type="xsd:string" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu14419.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="V" name="remain.v" ID="14419" frame="Existence" frameID="660" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="A9A9A9" type="Extra-Thematic" abbrev="Cause" name="Cause"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Extra-Thematic" abbrev="Circumstances" name="Circumstances"/>
            <FE fgColor="FFFFFF" bgColor="1E90FF" type="Extra-Thematic" abbrev="" name="Concessive"/>
            <FE fgColor="000000" bgColor="EEE8AA" type="Extra-Thematic" abbrev="" name="Depictive"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Extra-Thematic" abbrev="Dur" name="Duration"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="Ent" name="Entity"/>
            <FE fgColor="FFFFFF" bgColor="800080" type="Extra-Thematic" abbrev="Use" name="Inherent_purpose"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Peripheral" abbrev="Place" name="Place"/>
            <FE fgColor="FFFFFF" bgColor="9F79EE" type="Extra-Thematic" abbrev="pov" name="Point_of_view"/>
            <FE fgColor="FFFFFF" bgColor="A52A2A" type="Extra-Thematic" abbrev="" name="State"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Peripheral" abbrev="Time" name="Time"/>
        </frame>
    </header>
    <definition>COD: be in the same place or condition during further time.</definition>
    <lexeme POS="V" name="remain"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu15369.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Insufficient_Attestations" POS="N" name="v.n" ID="15369" frame="Shapes" frameID="328" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="A52A2A" type="Peripheral" abbrev="" name="Count"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="" name="Shape"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Peripheral" abbrev="" name="Shape_prop"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="" name="Substance"/>
        </frame>
    </header>
    <definition>FN: shaped like the letter 'V'</definition>
    <lexeme POS="N" name="v"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu12491.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="N" name="high-water mark.n" ID="12491" frame="Extreme_point" frameID="1573" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="ent" name="Entity"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Core" abbrev="mar" name="Marker"/>
        </frame>
    </header>
    <definition>COD: a maximum recorded level or value.</definition>
    <lexeme order="1" headword="true" breakBefore="false" POS="N" name="high-water"/>
    <lexeme order="2" headword="false" breakBefore="false" POS="N" name="mark"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu11272.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="V" name="pat down.v" ID="11272" frame="Inspecting" frameID="1262" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="A52A2A" type="Extra-Thematic" abbrev="cir" name="Circumstances"/>
            <FE fgColor="FFFFFF" bgColor="A9A9A9" type="Peripheral" abbrev="deg" name="Degree"/>
            <FE fgColor="FFFFFF" bgColor="00BFFF" type="Core" abbrev="des" name="Desired_state"/>
            <FE fgColor="FFFFFF" bgColor="0000FF" type="Core" abbrev="gro" name="Ground"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="insp" name="Inspector"/>
            <FE fgColor="FFFFFF" bgColor="9F79EE" type="Peripheral" abbrev="inst" name="Instrument"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Extra-Thematic" abbrev="loc" name="Location_of_inspector"/>
            <FE fgColor="FFFFFF" bgColor="FF69B4" type="Peripheral" abbrev="man" name="Manner"/>
            <FE fgColor="FFFFFF" bgColor="9400D3" type="Peripheral" abbrev="mea" name="Means"/>
            <FE fgColor="FFFFFF" bgColor="7CCD73" type="Extra-Thematic" abbrev="" name="Particular_iteration"/>
            <FE fgColor="FFFFFF" bgColor="FFA500" type="Core" abbrev="pur" name="Purpose"/>
            <FE fgColor="00008B" bgColor="d0d0d0" type="Peripheral" abbrev="tim" name="Time"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Core" abbrev="unw" name="Unwanted_entity"/>
        </frame>
    </header>
    <definition>FN: to tap with the hand over a person's body in search of unwanted things carried </definition>
    <lexeme order="1" headword="true" breakBefore="false" POS="V" name="pat"/>
    <lexeme order="2" headword="false" breakBefore="true" POS="ADV" name="down"/>
    <valences/>
</lexUnit>

=== FabianFriedrich/Text2Process/resources/fndata-1.5/lu/lu12583.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="lexUnit.xsl"?>
<lexUnit status="Created" POS="PREP" name="through the roof.prep" ID="12583" frame="Position_on_a_scale" frameID="95" totalAnnotated="0" xsi:schemaLocation="../schema/lexUnit.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <frame>
            <FE fgColor="FFFFFF" bgColor="FF69B4" type="Peripheral" abbrev="" name="Degree"/>
            <FE fgColor="FFFFFF" bgColor="008000" type="Peripheral" abbrev="" name="Domain"/>
            <FE fgColor="FFFFFF" bgColor="FF0000" type="Core" abbrev="Item" name="Item"/>
            <FE fgColor="FFFFFF" bgColor="00008B" type="Core-Unexpressed" abbrev="Val" name="Value"/>
            <FE fgColor="FFFFFF" bgColor="9400D3" type="Core" abbrev="Var" name="Variable"/>
        </frame>
    </header>
    <definition>FN: extremely high</definition>
    <lexeme order="1" headword="true" breakBefore="false" POS="PREP" name="through"/>
    <lexeme order="2" headword="false" breakBefore="false" POS="ART" name="the"/>
    <lexeme order="3" headword="false" breakBefore="false" POS="N" name="roof"/>
    <valences/>
</lexUnit>
